# Generated by Django 5.1.6 on 2025-03-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabanlingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
