# Generated by Django 5.1.6 on 2025-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabanlingo', '0002_customuser_age_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_lesson',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hearts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learn_lang',
            field=models.CharField(default='de', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
