# Generated by Django 5.1.6 on 2025-03-08 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabanlingo', '0004_customuser_creation_date_customuser_section_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='zabanlingo.section')),
            ],
            options={
                'ordering': ['section', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='zabanlingo.unit')),
            ],
            options={
                'ordering': ['unit', 'id'],
            },
        ),
    ]
