# Generated by Django 5.1.6 on 2025-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='ترتیب نمایش چالش در هر درس'),
        ),
    ]
