# Generated by Django 5.1.6 on 2025-02-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_challenge_options_challenge_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True, help_text='مروری کلی بر درس', null=True)),
                ('objectives', models.TextField(blank=True, help_text='اهداف آموزشی درس', null=True)),
                ('content', models.TextField(blank=True, help_text='محتوای آموزشی تکمیلی', null=True)),
                ('resources', models.JSONField(blank=True, help_text='منابع و لینک\u200cهای مرتبط', null=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='myapp.lesson')),
            ],
        ),
    ]
