# Generated by Django 5.1.6 on 2025-02-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_lessondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of the challenge within the lesson'),
        ),
    ]
