# Generated by Django 5.1.6 on 2025-03-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_challenge_correct_answer_alter_challenge_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='lesson_note',
            field=models.TextField(blank=True, help_text='درسنامه یا توضیحات مرتبط با چالش', null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='ترتیب چالش در درس'),
        ),
    ]
