# Generated by Django 5.1.6 on 2025-03-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_challenge_lesson_note_alter_challenge_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='code_snippet_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
